[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "physpy"
version = "0.0.1"
description = "Physics Lab library"
readme = "README.md"

[tool.hatch.version]
path = "physpy/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["physpy"]
